version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --user aws-sam-cli
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
  pre_build:
    on-failure: ABORT
    commands:
      - python3 test.py
  build:
    on-failure: ABORT
    commands:
  post_build:
    commands:
      - aws lambda update-function-code --function-name spotify_run
      - python3 test.py