version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --user aws-sam-cli
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
  pre_build:
    on-failure: ABORT
    commands:
      - python3 test.py
  build:
    on-failure: ABORT
    commands:
      - make codebuild-push-to-ecr
      - make codebuild-delete-untagged-images
  post_build:
    commands:
      - for d in elastic-etl-v3; do (cd "$d" && sam deploy --s3-bucket cloud9-697856758640-sam-deployments-us-west-2 --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --stack-name `cat .application.json | python3 -c "import sys, json; print(json.load(sys.stdin)['StackName'])"`); done
      - make codebuild-install
      #- for din elastic-etl-v1/common elastic-etl-v2/common ; do if [ -e $d/"stepFunctionDefinitions/sfnDeploy.py" ]; then (cd $d"/stepFunctionDefinitions" && python3 sfnDeploy.py); fi; done